### ISSUE TITLE
Apprise not loading on local test system

### ISSUE THREAD

**Issue by HandyGuySoftware** [HandyGuySoftware/dupReport#100]
xxxx@xxxx:~/dupReport$ dupReport.py
Traceback (most recent call last):
  File "./dupReport.py", line 172, in <module>
    globs.appriseObj = dupapprise.dupApprise()
  File "/home/xxxxx/dupReport/dupapprise.py", line 27, in __init__
    import apprise
ImportError: No module named 'apprise'

**Comment by HandyGuySoftware** [comment]
Was running Python 3 but apprise for python2 was loaded. Installed pip3 (sudo apt-get -y install python3-pip) and it worked.
