### ISSUE TITLE
[SOLVED] IMAP problem: ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:847)

### ISSUE THREAD

**Issue by bbccdd** [HandyGuySoftware/dupReport#116]
Hi all.

When trying to connect to an IMAP server for a dupReport, I get the following error on Ubuntu 18.04 using python3:

`ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:847)`

What could I look into in order to resolve this issue?

I have already started over with a fresh git clone and made sure that I copy'n pasted the working values from thunderbird. I have cencured the passwords and email addresses.

**Configuration** (cencured):
```
[main]
version = 2.2.6
dbpath = /opt/bcp/duplicati/_conf/dupReport
logpath = /opt/bcp/duplicati/_conf/dupReport
verbose = 1
logappend = false
subjectregex = ^Duplicati Backup report for
srcregex = \w*
destregex = \w*
srcdestdelimiter = @
dateformat = DD/MM/YYYY
timeformat = HH:MM:SS
warnoncollect = false
applyutcoffset = true
show24hourtime = true
purgedb = false
showprogress = 0
masksensitive = true
markread = false

[incoming]
intransport = imap
inserver = imap.freedom.nl
inport = 143
inencryption = tls
inaccount = user@freedom.nl
inpassword = secret
infolder = INBOX
inkeepalive = false

[outgoing]
outserver = smtp.freedom.nl
outport = 587
outencryption = tls
outsender = Backup Report Duplicati dupReport <more@freedom.nl>
outreceiver = my@email.com
outkeepalive = false
outaccount = user@freedom.nl
outpassword = secret

[report]
style = srcdest
sortby = source
border = 1
padding = 5
reporttitle = Duplicati Backup Summary Report
sizedisplay = giga
showsizedisplay = true
displaymessages = false
displaywarnings = true
displayerrors = true
titlebg = #FFFFFF
subheadbg = #D3D3D3
jobmessagebg = #FFFFFF
jobwarningbg = #FFFF00
joberrorbg = #FF0000
repeatheaders = false
nobackupwarn = 0
nbwsubject = Backup Warning: #SOURCE##DELIMITER##DESTINATION# Backup Not Seen for #DAYS# Days
lastseensummary = none
lastseensummarytitle = Backup Sets Last Seen
lastseenlow = 5
lastseenmed = 10
lastseenlowcolor = #FFFF00
lastseenmedcolor = #FF4500
lastseenhighcolor = #FF0000
truncatemessage = 0
truncatewarning = 0
truncateerror = 0
durationzeroes = true

[headings]
source = Source
destination = Destination
date = Date
time = Time
duration = Duration
files = Files
filesplusminus = +/-
size = Size
sizeplusminus = +/-
added = Added
deleted = Deleted
modified = Modified
errors = Errors
result = Result
jobmessages = Messages
jobwarnings = Warnings
joberrors = Errors
```

**Logfile**
```
******** dupReport Log - Start: Wed May 22 16:01:22 2019
Program Version 2.2.6 Release
Database Version 1.0.2
Python version 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0]
initOptions()
Processing command line...
options.processCmdLineArgs()
Command line parsed:
- rcpath = [None]
- dbpath = [None]
- logpath = [None]
- verbose = [None]
- Version = [False]
- append = [False]
- size = [None]
- initdb = [False]
- rollback = [None]
- rollbackx = [None]
- file = [None]
- nomail = [False]
- remove = [None]
- purgedb = [False]
- stopbackupwarn = [False]
- collect = [False]
- report = [False]
- masksensitive = [False]
- nomasksensitive = [False]
RC path not specified on command line. Using default.
Final RC path=[***********************************************]
options.openRcFile(***********************************************)
options.checkRcFileVersion()
RC file versions: current=226 new=210.
Current version number=226. Need to upgrade rc file? False
options.setRcDefaults()
rc.setDefaults(***********************************************)
newRc=False
options.readRcOptions(***********************************************)
Parsed config option [rcfilename]=[***********************************************]
Parsed config option [version]=[False]
Parsed config option [dbpath]=[***********************************************]
Parsed config option [logpath]=[************************************************]
Parsed config option [verbose]=[1]
Parsed config option [logappend]=[False]
Parsed config option [subjectregex]=[^Duplicati Backup report for]
Parsed config option [srcregex]=[\w*]
Parsed config option [destregex]=[\w*]
Parsed config option [srcdestdelimiter]=[@]
Parsed config option [dateformat]=[DD/MM/YYYY]
Parsed config option [timeformat]=[HH:MM:SS]
Parsed config option [warnoncollect]=[False]
Parsed config option [applyutcoffset]=[True]
Parsed config option [show24hourtime]=[True]
Parsed config option [purgedb]=[False]
Parsed config option [showprogress]=[0]
Parsed config option [masksensitive]=[True]
Parsed config option [markread]=[False]
Parsed config option [intransport]=[imap]
Parsed config option [inserver]=[***************]
Parsed config option [inport]=[143]
Parsed config option [inencryption]=[tls]
Parsed config option [inaccount]=[***************]
Parsed config option [inpassword]=[********************]
Parsed config option [infolder]=[INBOX]
Parsed config option [inkeepalive]=[False]
Parsed config option [outserver]=[***************]
Parsed config option [outport]=[587]
Parsed config option [outencryption]=[tls]
Parsed config option [outsender]=[***************************************************]
Parsed config option [outreceiver]=[******************]
Parsed config option [outkeepalive]=[False]
Parsed config option [outaccount]=[***************]
Parsed config option [outpassword]=[********************]
Parsed config option [collect]=[False]
Parsed config option [report]=[False]
Parsed config option [nomail]=[False]
Parsed config option [remove]=[None]
Parsed config option [stopbackupwarn]=[False]
Parsed config option [rollback]=[None]
Parsed config option [rollbackx]=[None]
Parsed config option [initdb]=[False]
Parsed config option [file]=[None]
Need to restart? False
Program initialization complete. Continuing program.
Database.__init__(***********************************************)
Database.checkDbVersion()
Database.execSqlStmt(): Executing SQL command.
Logfile=[************************************************]  appendlog=[False]  logLevel=[1]
dbPath=[***********************************************]  rcpath=[***********************************************]
Database.execSqlStmt(): Executing SQL command.
Database.dbCommit(): Committing transaction.
EmailServer.Connect()
Initial connect using  IMAP
```

**Error**
```
root@host:/opt/bcp/duplicati/_conf/dupReport# python3 /opt/bcp/duplicati/_conf/dupReport/dupReport.py
Traceback (most recent call last):
  File "/opt/bcp/duplicati/_conf/dupReport/dupReport.py", line 232, in <module>
    newMessages = globs.inServer.checkForMessages()
  File "/opt/bcp/duplicati/_conf/dupReport/dremail.py", line 192, in checkForMessages
    self.connect()
  File "/opt/bcp/duplicati/_conf/dupReport/dremail.py", line 131, in connect
    self.server = imaplib.IMAP4_SSL(self.address,self.port)
  File "/usr/lib/python3.6/imaplib.py", line 1288, in __init__
    IMAP4.__init__(self, host, port)
  File "/usr/lib/python3.6/imaplib.py", line 198, in __init__
    self.open(host, port)
  File "/usr/lib/python3.6/imaplib.py", line 1301, in open
    IMAP4.open(self, host, port)
  File "/usr/lib/python3.6/imaplib.py", line 299, in open
    self.sock = self._create_socket()
  File "/usr/lib/python3.6/imaplib.py", line 1293, in _create_socket
    server_hostname=self.host)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:847)
root@host:/opt/bcp/duplicati/_conf/dupReport# 
```

**Comment by HandyGuySoftware** [comment]
Hi @bbccdd, is this the first time running/using dupReport or has it been working for a while and just started crashing with this error?

**Comment by bbccdd** [comment]
Hi. I had been running dupReport for a few months on the same server last year (ubuntu 16.04 back then), but against a different IMAP server.

**Comment by HandyGuySoftware** [comment]
The standard port for IMAP SSL/TLS is 993 but you have port 143 set. This may be a shot in the dark before digging deeper in the code, but try changing [incoming] inport = 993 in the .rc file to see if that helps.

**Comment by bbccdd** [comment]
Fixed :-) Indeed, although only port 143 was published, port 993 did the trick. Thank you!

**Comment by HandyGuySoftware** [comment]
Glad you solved it! Thanks for using the software!
