### ISSUE TITLE
"Nonetype has no attribute groups" - dupreport crash

### ISSUE THREAD

**Issue by jdeluyck** [HandyGuySoftware/dupReport#177]
Hi,

I'm starting off with dupReport (also trying to dockerize it), and I keep hitting a crash with the following stacktrace:

```
$ dupReport/dupReport.py --rcpath config -v 7
Traceback (most recent call last):
  File "/home/devilkin/source/dupreport-docker/dupReport/dupReport.py", line 138, in <module>
    globs.emailManager.checkForNewMessages()
  File "/home/devilkin/source/dupreport-docker/dupReport/dremail.py", line 144, in checkForNewMessages
    nxtMsg = self.incoming[server].processNextMessage()
  File "/home/devilkin/source/dupreport-docker/dupReport/dremail.py", line 515, in processNextMessage
    if (len(m.groups()) != 2):    # Correct subject but delimeter not found. Something is wrong.
AttributeError: 'NoneType' object has no attribute 'groups'
```

I'm using `subjectregex = ^Duplicati ([\w ]*, |)Backup report for`, and in duplicati itself it's configured with `--send-mail-subject=Duplicati %PARSEDRESULT%, %OPERATIONNAME% report for %backup-name%`.

I'm not sure what exactly it tries to look for here. The Subject of the mail is:

```
Date: Sat, 30 Oct 2021 05:11:15 +0200
Subject: Duplicati Warning, Backup report for Backup  to B2
Message-Id: <0DMBF07X5FU4.REGF8LNHMAX31@25dcfd5f32f2>
```

The log shows
```
[2021-12-29T21:02:04.055624][DEBUG][EmailServer][processNextMessage]Server.fetch(): retVal=[OK] data=[[(b'1 (BODY[HEADER.FIELDS (DATE SUBJECT MESSAGE-ID CONTENT-TRANSFER-ENCODING)] {190}', b'Date: Sat, 30 Oct 2021 05:11:15 +0200\r\nSubject: Duplicati Warning, Backup report for Backup  to B2\r\nMessage-Id: <0DMBF07X5FU4.REGF8LNHMAX31@25dcfd5f32f2>\r\nContent-Transfer-Encoding: 7bit\r\n\r\n'), b')']]
[2021-12-29T21:02:04.055831][NOTICE][EmailServer][extractHeaders]Extracting headers from (Date: Sat, 30 Oct 2021 05:11:15 +0200^M
Subject: Duplicati Warning, Backup report for Backup  to B2^M
Message-Id: <0DMBF07X5FU4.REGF8LNHMAX31@25dcfd5f32f2>^M
Content-Transfer-Encoding: 7bit^M
^M
)
[2021-12-29T21:02:04.055998][NOTICE][EmailServer][extractHeaders]Header fields extracted: [{'date': 'Sat, 30 Oct 2021 05:11:15 +0200', 'subject': 'Duplicati Warning, Backup report for Backup  to B2', 'message-id': '<0DMBF07X5FU4.REGF8LNHMAX31@25dcfd5f32f2>', 'content-transfer-encoding': '7bit'}]
[2021-12-29T21:02:04.056044][DEBUG][EmailServer][processNextMessage]Next Message: headers=[{'date': 'Sat, 30 Oct 2021 05:11:15 +0200', 'subject': 'Duplicati Warning, Backup report for Backup  to B2', 'messageId': '<0DMBF07X5FU4.REGF8LNHMAX31@25dcfd5f32f2>', 'content-transfer-encoding': '7bit'}]
[2021-12-29T21:02:04.056922][DEBUG][EmailServer][processNextMessage]subjectregex='[^Duplicati ([\w ]*, |)Backup report for]' srcregex='[\w*]' srcdelimiter='[-]' destregex='[\w*]'
```

**Comment by HandyGuySoftware** [comment]
@jdeluyck , thanks for submitting this.

dupReport needs a Duplicati backup name to be in the form `<source><delimeter><destination>` without any spaces in between. For example, `MediaServer-NAS`. The delimeter should be a single character that does not appear elsewhere in your backup names. In the example, this would be '-'.

Your backup name is shown as `Backup  to B2`. but your .rc file specifies the delimiter as '-' (the default). Since the program can't find a '-' anywhere in the subject line it is unable to properly parse the subject line and won't see this as a valid email.

To fix this problem, simply use a '-' between the source and destination in your backup name, like `Backup-B2`. You can use any delimiter you like instead of '-', just make sure to change the `srcdestdelimiter=` field in the .rc file to whatever you choose.

That being said, however, the program should detect the error and simply skip the email rather than crashing, as you experienced. The subject parsing routine was recently modified and this appears to have introduced this error into the code. I will work on getting that updated in the next release.

One last note; there are ways to include spaces in your backup names and delimiter (though it's not recommended). If that's something you're interested in, please see the recent discussion for Issue #174 to see how it can be done.

Let me know if that suggestion fixes your issue.

HG

**Comment by jdeluyck** [comment]
Ah, yeah, this makes sense. I read through the documentation at first but the source-destination thing didn't really click in how it was used, and now it does. 

I've changed the name of the job, let's see what happens now. Thanks.

**Comment by HandyGuySoftware** [comment]
I have made updates to the code and uploaded it to the [Issue_177 branch on GitHub](https://github.com/HandyGuySoftware/dupReport/tree/Issue_177). This should fix the crash you experienced. I've also updated the documentation on specifying source and destination within the system to hopefully explain it better. if you can download this branch and try it out it should work fine (or at least better).

**Comment by jdeluyck** [comment]
I can confirm it no longer crashes. Thanks!

**Comment by HandyGuySoftware** [comment]
Added to 3.0.8 release.

**Comment by HitLuca** [comment]
@jdeluyck did you ever end up containerizing this service?

**Comment by jdeluyck** [comment]
> @jdeluyck did you ever end up containerizing this service?

If memory serves me right yes, but I stopped using Duplicati, and trashed the containers + config. So I can't readily help you.
