### ISSUE TITLE
Handling failed backups

### ISSUE THREAD

**Issue by dcurrey** [HandyGuySoftware/dupReport#7]
If dupreport tries to parse a failed upload it gives errors.   In this case a simple aborted upload.

Temporary workaround was to add advance option in duplicatii editing they way mail subject is displayed.
~~~
--send-mail-subject=Duplicati %OPERATIONNAME% (%PARSEDRESULT%) report for %backup-name%
~~~
This create the subject of "Duplicati Backup (Success) report for somebackup-somedest"

Then edit the dupReport.rc file changing the subjectregex setting
~~~
subjectregex = ^Duplicati Backup \(Success\) report for
~~~
DupReport now should only process successful backups. You may to need to look at some kind of option to notify users when dupreport encounter a failed or warning status for %PARSEDRESULT% from the subject line.

**Comment by dcurrey** [comment]
After thinking about this some more I think subjectregex should be something like
~~~
subjectregex = ^Duplicati Backup \((Success|Error|Warn)\) report for
~~~
Assuming duplicati creates the proper output with Error and Warn dR will process the ParsedResult: in the email correctly.   Not sure how to force Duplicati to create a warning/error message now that I need one.

Something separate to handle the Fatal error that %PARSEDRESULT% = Fatal is all that is needed

**Comment by HandyGuySoftware** [comment]
Great work-around. Part of the 'philosophy' of dR was to try to work with as much of Duplicati's defaults as possible, including handling abnormal emails coming in. I thought I had done this, but apparently not well enough. The subjectregex param was added for 'tinkerers' but Duplicati is hard enough to configure without laying this on a newbie. I'd like to try to trace the original problem and build its handling into the code. Can you send/post a 'failed' email sample ( as many different types as you have) so I can see what dR is trying to parse and hopefully come up with a clean handler for it?

**Comment by dcurrey** [comment]
No problem here is the error generated from my second forced abort.
~~~
Return-Path: <dupreport@mail2.domain.com>
Delivered-To: dupreport@mail2.domain.com
Received: from localhost (localhost.localdomain [127.0.0.1])
	by beta.domain.com (Postfix) with ESMTP id 887AB45429D1
	for <dupreport@mail2.domain.com>; Tue, 24 Oct 2017 15:47:15 -0400 (EDT)
X-Virus-Scanned: Debian amavisd-new at beta.domain.com
Received: from beta.domain.com ([127.0.0.1])
	by localhost (beta.domain.com [127.0.0.1]) (amavisd-new, port 10026)
	with ESMTP id WxfKZyOC7gxU for <dupreport@mail2.domain.com>;
	Tue, 24 Oct 2017 15:47:14 -0400 (EDT)
Received: from [192.168.1.11] (dsl-1-86-85-12.some.net [1.86.85.12])
	(using TLSv1 with cipher AES256-SHA (256/256 bits))
	(No client certificate requested)
	(Authenticated sender: dupreport@mail2.domain.com)
	by beta.domain.com (Postfix) with ESMTPSA id 778A24542650
	for <dupreport@mail2.domain.com>; Tue, 24 Oct 2017 15:47:14 -0400 (EDT)
From: Duplicati <dupreport@mail2.domain.com>
Date: Tue, 24 Oct 2017 15:47:13 -0400
Subject: Duplicati Backup (Fatal) report for test@ddc3
Message-Id: <6INB1DQRO2U4.7SU3SZ24TUJ83@DDC3>
To: DupReport <dupreport@mail2.domain.com>
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 7bit

Failed: Object reference not set to an instance of an object
Details: System.NullReferenceException: Object reference not set to an instance of an object
  at Duplicati.Library.Main.Volumes.VolumeWriterBase.get_Filesize () [0x00000] in <82db7c3af7d944569906ea5ff7f18985>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.RecreateMissingIndexFiles (Duplicati.Library.Main.BackendManager backend) [0x001c9] in <82db7c3af7d944569906ea5ff7f18985>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.Run (System.String[] sources, Duplicati.Library.Utility.IFilter filter) [0x00553] in <82db7c3af7d944569906ea5ff7f18985>:0 
~~~

Looking back I found my first one it is slightly different.
I left out most of the message headers
~~~
From: Duplicati <dupreport@mail2.domain.com>
Date: Tue, 24 Oct 2017 15:47:13 -0400
Subject: Duplicati Backup (Fatal) report for test@ddc3
Message-Id: <6INB1DQRO2U4.7SU3SZ24TUJ83@DDC3>
To: DupReport <dupreport@mail2.domain.com>
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 7bit

Failed: Thread was being aborted.
Details: System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Threading.WaitHandle.WaitOneNative(SafeHandle waitableSafeHandle, UInt32 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at System.Threading.WaitHandle.InternalWaitOne(SafeHandle waitableSafeHandle, Int64 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at System.Threading.WaitHandle.WaitOne(Int32 millisecondsTimeout, Boolean exitContext)
   at Duplicati.Library.Utility.BlockingQueue`1.Enqueue(T item)
   at Duplicati.Library.Main.BackendManager.WaitForEmpty(LocalDatabase db, IDbTransaction transation)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   at Duplicati.Library.Main.Controller.<>c__DisplayClass16_0.<Backup>b__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
~~~

**Comment by dcurrey** [comment]
Here is another
~~~
Failed: The process cannot access the file because it is being used by another process.
Details: System.IO.IOException: The process cannot access the file because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Duplicati.Library.Main.Operation.RepairHandler.Run(IFilter filter)
   at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend, String protectedfile)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   at Duplicati.Library.Main.Controller.<>c__DisplayClass16_0.<Backup>b__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
~~~
At a glance it looks like if dR parses that first failed line properly and drop the rest you might be ok without changing the subject.

**Comment by HandyGuySoftware** [comment]
I have this on the run now. Thanks for the samples. New code will gracefully handle and report failed backup jobs without changing the Subject line specification (and without crashing :-):

![image](https://user-images.githubusercontent.com/16890568/32053976-80f9f3d0-ba22-11e7-8a6e-004dde51efa1.png)

It may be a couple of days before I can clean the code and upload to the beta branch. Also adding a couple of other fixes while I'm at it. Will notify when ready to test.

**Comment by HandyGuySoftware** [comment]
Committed to beta branch for testing.
