### ISSUE TITLE
Attribute error in message_from_string()

### ISSUE THREAD

**Issue by HandyGuySoftware** [HandyGuySoftware/dupReport#71]
Traceback (most recent call last):
  File "./dupReport.py", line 215, in <module>
    nxtMsg = globs.inServer.getNextMessage()
  File "/home/home.friedfamily.net/parents/dupReport/dremail.py", line 220, in getNextMessage
    retMessage = email.message_from_string(data[0][1].decode('utf-8'))  # Get message body
AttributeError: 'int' object has no attribute 'decode'

**Comment by HandyGuySoftware** [comment]
from [https://stackoverflow.com/questions/2230037/how-to-fetch-an-email-body-using-imaplib-in-python](https://stackoverflow.com/questions/2230037/how-to-fetch-an-email-body-using-imaplib-in-python)


> I am currently experiencing that data[0] is actually just a bytes object and not a tuple of (bytes, bytes). My application continuously polls for new (unseen) messages from the IMAP server and this behaviour occurs when I mark the message as unread from the web interface. The service is at web.de. More specifically, **_usually the data format is [(bytes, bytes), bytes] but when the message is marked as unseen manually, the format is [bytes, (bytes, bytes), bytes]_** – Niklas R Sep 8 '15 at 23:29

in dremail.py, need to check data returned from fetch() call. 
```
if len(data) == 2:
    retMessage = email.message_from_string(data[0][1].decode('utf-8'))  # Get message body
    globs.log.write(3,'data[0][1]=[{}]'.format(data[0][1]))
else:
    retMessage = email.message_from_string(data[1][1].decode('utf-8'))  # Get message body
    globs.log.write(3,'data[1][1]=[{}]'.format(data[0][1]))
```
