### ISSUE TITLE
Date/Time issue 2.1.0

### ISSUE THREAD

**Issue by ninja6o4** [HandyGuySoftware/dupReport#86]
I updated to the 2.1.0 master branch and now seem to have a date/time error again:

```
Traceback (most recent call last):
  File "dupReport.py", line 214, in <module>
    globs.inServer.processMessage(nxtMsg)
  File "C:\dupReport-2.1.0\dremail.py", line 457, in processMessage
    globs.log.write(3, 'endTimeStamp=[{}] beginTimeStamp=[{}]'.format(drdatetime.fromTimestamp(dateParts['endTimestamp']), drdatetime.fromTimestamp(dateParts['beginTimestamp'])))
  File "C:\dupReport-2.1.0\drdatetime.py", line 134, in fromTimestamp
    dt = datetime.datetime.fromtimestamp(float(ts))
TypeError: float() argument must be a string or a number, not 'NoneType'
```

Log snippet:
```
statusParts['failed']=[]
options.getRcSectionDateTimeFmt(xxx_I5_10, Backup Server)
drDateTime.toTimestamp(2018-02-10 12:00:12 AM, YYYY-MM-DD, HH:MM:SS, -28800)
Date/Time converted to [1518220812.0]
drDateTime.toTimestamp(2018-02-10 12:00:00 AM, None, None, -28800)
drdatetime.fromTimestamp(1518220812.0, MM/DD/YYYY, HH:MM:SS)
Converted [1518220812.0] to [02/09/2018 16:00:12]
drdatetime.fromTimestamp(None, MM/DD/YYYY, HH:MM:SS)
```

In the .rc file:
```
[xxx_I5_10-Backup Server]
dateformat = YYYY-MM-DD
timeformat = HH:MM:SS
```

**Comment by ninja6o4** [comment]
Hmm.. updated to 2.2 pre_prod and the problem doesn't occur. I'll leave it this way and close the issue.
